CREATE TABLE "plataforma_geral"."projetos_ativos" ( 
  "id" SERIAL,
  "pipefy_id" INTEGER NOT NULL,
  "nome" VARCHAR(250) NULL,
  "documento" VARCHAR(250) NULL,
  "fee" INTEGER NULL,
  "moeda" VARCHAR(6) NULL,
  "squad_atribuida" VARCHAR(20) NULL,
  "produto_contratado" VARCHAR(250) NULL,
  "data_de_inicio" DATE NULL,
  "cohort" VARCHAR(100) NULL,
  "meta_account_id" VARCHAR(100) NULL,
  "google_account_id" VARCHAR(100) NULL,
  "fase_do_pipefy" VARCHAR(100) NULL,
  "url_webhook_gchat" VARCHAR(250) NULL,
  "step" VARCHAR(15) NULL,
  "informacoes_gerais" VARCHAR(1500) NULL,
  "orcamento_midia_meta" INTEGER NULL,
  "orcamento_midia_google" INTEGER NULL,
  "data_fim" DATE NULL,
  "extra" JSONB NULL,
  "notas" JSONB NULL,
  "ekyte_workspace" VARCHAR(2500) NULL,
  CONSTRAINT "projetos_ativos_pkey" PRIMARY KEY ("pipefy_id")
);
