# Generated by Django 6.0a1 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('funcao', models.CharField(blank=True, max_length=50, null=True)),
                ('senioridade', models.CharField(blank=True, max_length=50, null=True)),
                ('squad', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(db_column='senha', max_length=250)),
                ('nivel_acesso', models.CharField(default='Usuário', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nivel', models.TextField(blank=True, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=250, null=True)),
                ('posicao', models.CharField(blank=True, max_length=250, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."investidores"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '"plataforma_geral"."auth"',
                'managed': False,
            },
        ),
    ]
