# Generated by Django 6.0a1 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestidorProjeto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_investidor', models.CharField(max_length=250)),
                ('pipefy_id_projeto', models.IntegerField()),
                ('active', models.BooleanField()),
                ('inactivated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('cientista', models.BooleanField()),
                ('nome_projeto', models.CharField(blank=True, max_length=250, null=True)),
                ('fee_projeto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee_contribuicao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."investidores_projetos"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoAtivo',
            fields=[
                ('pipefy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=250, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('moeda', models.CharField(blank=True, max_length=6, null=True)),
                ('squad_atribuida', models.CharField(blank=True, max_length=20, null=True)),
                ('produto_contratado', models.CharField(blank=True, max_length=250, null=True)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_do_pipefy', models.CharField(blank=True, max_length=100, null=True)),
                ('url_webhook_gchat', models.CharField(blank=True, max_length=250, null=True)),
                ('step', models.CharField(blank=True, max_length=15, null=True)),
                ('informacoes_gerais', models.CharField(blank=True, max_length=1500, null=True)),
                ('orcamento_midia_meta', models.IntegerField(blank=True, null=True)),
                ('orcamento_midia_google', models.IntegerField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('notas', models.JSONField(blank=True, null=True)),
                ('ekyte_workspace', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."projetos_ativos"',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoInativo',
            fields=[
                ('pipefy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=250, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('moeda', models.CharField(blank=True, max_length=6, null=True)),
                ('squad_atribuida', models.CharField(blank=True, max_length=20, null=True)),
                ('produto_contratado', models.CharField(blank=True, max_length=250, null=True)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_do_pipefy', models.CharField(blank=True, max_length=100, null=True)),
                ('url_webhook_gchat', models.CharField(blank=True, max_length=250, null=True)),
                ('step', models.CharField(blank=True, max_length=15, null=True)),
                ('informacoes_gerais', models.CharField(blank=True, max_length=1500, null=True)),
                ('orcamento_midia_meta', models.IntegerField(blank=True, null=True)),
                ('orcamento_midia_google', models.IntegerField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('notas', models.JSONField(blank=True, null=True)),
                ('ekyte_workspace', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."projetos_inativos"',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoOnetime',
            fields=[
                ('pipefy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=250, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('moeda', models.CharField(blank=True, max_length=6, null=True)),
                ('squad_atribuida', models.CharField(blank=True, max_length=20, null=True)),
                ('produto_contratado', models.CharField(blank=True, max_length=250, null=True)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_do_pipefy', models.CharField(blank=True, max_length=100, null=True)),
                ('url_webhook_gchat', models.CharField(blank=True, max_length=250, null=True)),
                ('step', models.CharField(blank=True, max_length=15, null=True)),
                ('informacoes_gerais', models.CharField(blank=True, max_length=1500, null=True)),
                ('orcamento_midia_meta', models.IntegerField(blank=True, null=True)),
                ('orcamento_midia_google', models.IntegerField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('notas', models.JSONField(blank=True, null=True)),
                ('ekyte_workspace', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."projetos_onetime"',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
