# Generated by Django 6.0a1 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaMensal',
            fields=[
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('email_investidor', models.TextField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('senioridade', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('flag', models.TextField(blank=True, null=True)),
                ('motivo_flag', models.TextField(blank=True, null=True)),
                ('green_streak', models.IntegerField(blank=True, null=True)),
                ('yellow_streak', models.IntegerField(blank=True, null=True)),
                ('fixo_mrr_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_entrega', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_churn_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_remuneracao_fixa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_csp_esperado', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('fixo_churn_maximo_percentual', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('fixo_mrr_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_teto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_churn_maximo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_remuneracao_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_remuneracao_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_projeto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calc_churn_real_percentual', models.DecimalField(blank=True, decimal_places=7, editable=False, max_digits=8, null=True)),
                ('calc_delta_churn_percentual', models.DecimalField(blank=True, decimal_places=7, editable=False, max_digits=8, null=True)),
                ('calc_delta_churn_valor', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('calc_variavel_churn', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('calc_delta_csp', models.DecimalField(blank=True, decimal_places=7, editable=False, max_digits=8, null=True)),
                ('calc_variavel_csp', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('calc_variavel_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('calc_remuneracao_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('historico_projetos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."investidores_metricas_mensais_novo"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RemuneracaoCargo',
            fields=[
                ('fixo_cargo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fixo_senioridade', models.CharField(max_length=50)),
                ('fixo_level', models.CharField(max_length=50)),
                ('fixo_ticket_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_mrr_teto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_remuneracao_fixa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixo_churn_maximo_percentual', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('calc_mrr_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calc_remuneracao_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calc_remuneracao_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calc_csp_esperado', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('calc_churn_maximo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."remuneracao_cargos"',
                'managed': False,
            },
        ),
    ]
