# Generated by Django 6.0a1 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('client_id', models.IntegerField()),
                ('email', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fee_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mrr_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."monthly_deliveries"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_pipefy_id', models.IntegerField()),
                ('investidor_email', models.TextField()),
                ('semana_ano', models.CharField(max_length=20)),
                ('compareceu', models.BooleanField(default=False)),
                ('campanhas_ativas', models.BooleanField(default=True)),
                ('gap_comunicacao', models.BooleanField(default=False)),
                ('cliente_reclamou', models.BooleanField(default=False)),
                ('satisfeito', models.BooleanField(default=True)),
                ('csat_pontuacao', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_checkins"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoEntregaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investidor_email', models.TextField()),
                ('projeto_pipefy_id', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('entrega_1', models.BooleanField(default=False)),
                ('entrega_2', models.BooleanField(default=False)),
                ('entrega_3', models.BooleanField(default=False)),
                ('entrega_4', models.BooleanField(default=False)),
                ('percentual_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('valor_fee_original', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_contribuicao_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_entregas_mensais"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoLinkUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_pipefy_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(default='fa-link', max_length=50)),
                ('criado_por', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_links_uteis"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoOtimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_pipefy_id', models.IntegerField()),
                ('investidor_email', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('canal', models.CharField(blank=True, max_length=50, null=True)),
                ('data_otimizacao', models.DateField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_otimizacoes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoPlanoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_pipefy_id', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('investidor_email', models.TextField()),
                ('dados_plano', models.JSONField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_planos_midia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_pipefy_id', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('concluida', models.BooleanField(default=False)),
                ('referencia', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"plataforma_geral"."operacao_tarefas"',
                'managed': False,
            },
        ),
    ]
